# Generated by Django 5.2.13 on 2026-05-03 16:58

import kosts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='room_images/', validators=[kosts.validators.validate_image_type, kosts.validators.validate_file_size]),
        ),
    ]
