# Generated by Django 5.2.13 on 2026-04-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='assignedKost',
            new_name='kost_id',
        ),
    ]
