# Generated by Django 5.2.13 on 2026-04-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_assignedkost_staff_kost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='kost_id',
            new_name='kost',
        ),
    ]
