# Generated by Django 5.2.13 on 2026-05-03 16:31

import storages.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='identity_card',
            field=models.ImageField(storage=storages.supabase_storage.SupabaseStorage(), upload_to='identity_cards/'),
        ),
    ]
