# Generated by Django 5.2.13 on 2026-05-03 16:58

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tenant_identity_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='identity_card',
            field=models.ImageField(upload_to='identity_cards/', validators=[api.validators.validate_image_type, api.validators.validate_ktp_image_size]),
        ),
    ]
