# Generated by Django 5.2.13 on 2026-04-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(),
        ),
    ]
