"""
Django settings for ibdakost project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv
import os
import sys

load_dotenv()  # Load environment variables from .env file  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zp)$j#*zq_)$nw0a9s-i5pvhwqmt_r8&ba7adl9!8i8ssp%yx)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "*" # untuk sementara, nanti diubah sesuai kebutuhan
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Sesuaikan dengan kebutuhan
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Sesuaikan
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Aplikasi yang sedang dibuat
    'api',
    'kosts',
    'rooms',
    'leases',
    'wishlists',
    'invoices',

    # Aplikasi pihak ketiga
    'rest_framework',
    'corsheaders',
    # 'storages',
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
#         "OPTIONS": {
#             "endpoint_url": os.getenv("AWS_S3_ENDPOINT_URL"),
#             "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
#             "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),
#             "bucket_name": os.getenv("AWS_STORAGE_BUCKET_NAME"),
#             "region_name": os.getenv("AWS_S3_REGION_NAME"),
#             "object_parameters": {
#                 "CacheControl": "max-age=86400",
#             },
#             "querystring_auth": True,
#             "location": "media",
#         },
#     },
#     "staticfiles": {
#         "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
#         "OPTIONS": {
#             "endpoint_url": os.getenv("AWS_S3_ENDPOINT_URL"),
#             "access_key": os.getenv("AWS_ACCESS_KEY_ID"),
#             "secret_key": os.getenv("AWS_SECRET_ACCESS_KEY"),  # 00
#             "bucket_name": os.getenv("AWS_STORAGE_BUCKET_NAME"),
#             "region_name": os.getenv("AWS_S3_REGION_NAME"),
#             "object_parameters": {
#                 "CacheControl": "max-age=86400",
#             },
#             "querystring_auth": True,
#             "location": "static",
#         },
#     },
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",  # Tambahkan middleware CORS
]

ROOT_URLCONF = 'ibdakost.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ibdakost.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    # 'default': {
    #     'ENGINE': os.getenv('DATABASE_ENGINE'),
    #     'NAME': os.getenv('DATABASE_NAME'),
    #     'USER': os.getenv('DATABASE_USER'),
    #     'PASSWORD': os.getenv('DATABASE_PASSWORD'),
    #     'HOST': os.getenv('DATABASE_HOST'),
    #     'PORT': os.getenv('DATABASE_PORT'),
    # }
    'default': dj_database_url.parse(os.getenv('DATABASE_URL'))
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'api.User'  # Gunakan model User kustom dari aplikasi api

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Ganti dengan URL frontend Anda
]
CORS_ALLOW_CREDENTIALS = True

# DEFAULT_FILE_STORAGE = "storages.supabase_storage.SupabaseStorage"

# SUPABASE_PROJECT_URL = os.getenv('SUPABASE_PROJECT_URL')
# SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
# SUPABASE_BUCKET = os.getenv("SUPABASE_BUCKET", "media")

if 'test' in sys.argv:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    # MEDIA_URL = '/media/'
    # MEDIA_ROOT = os.path.join(BASE_DIR, 'media')