@superuser_access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4NTI1Mzc5LCJpYXQiOjE3Nzg1MjE3NzksImp0aSI6ImE3ZWNmZjI1YWZmZTRmZTY5YTExMmMzNjg3ZWQ0NDJlIiwidXNlcl9pZCI6IjA1Y2I2MWExLWIxOGMtNGVhNy1iY2IxLWRjYTg4NGMzMjAxYiJ9.WsOd15lj04H5RO2guzop_4FFn6JQeTWMT7lg8mmcUWM
@tenant_access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3NTI3ODIyLCJpYXQiOjE3Nzc1MjQyMjIsImp0aSI6ImJlMTMwY2MzMTJiMjQzZDBhOGFlNTkxM2E4MDZjMzhjIiwidXNlcl9pZCI6IjAxYzQxZTVlLTUzMzItNDQwNS04MjhhLTIwNTllMjY1MzRiNSJ9.ePZp_oHGznzF6_vf1RPGSPPkGIkbHiN_JqUKToEvLJQ

@manager_access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4NTI1NDgwLCJpYXQiOjE3Nzg1MjE4ODAsImp0aSI6ImIwMDlkNDk3NjA5YTRhNjBhZTlkMDc5YjRkOWNmNGU3IiwidXNlcl9pZCI6IjMxZDkxMjAzLTliNjItNGYyYi1iMmNjLTU0NzJkN2FhNTBhYiJ9._kdtFh4Di0sScF3z_oXhLqYRW9meDNt-Ff1xM-7KA_c

GET http://localhost:8000/employees/ HTTP/1.1
Authorization: Bearer {{manager_access_token}}
Accept: application/json
Content-Type: application/json

# {
#     "email": "anyelir@gmail.com",
#     "password": "anyelir123"
# }