# Generated by Django 5.2.13 on 2026-04-25 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
