# Generated by Django 5.2.13 on 2026-05-03 16:31

import storages.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='image',
            field=models.ImageField(storage=storages.supabase_storage.SupabaseStorage(), upload_to='kost_images/'),
        ),
    ]
