# Generated by Django 5.2.13 on 2026-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosts', '0002_alter_kost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='image',
            field=models.ImageField(upload_to='kost_images/'),
        ),
    ]
