# Generated by Django 5.2.13 on 2026-05-03 16:58

import kosts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosts', '0003_alter_kost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='image',
            field=models.ImageField(upload_to='kost_images/', validators=[kosts.validators.validate_file_size, kosts.validators.validate_image_type]),
        ),
    ]
